#define MUR        'X'
#define PASSAGE    ' '
#define ENTREE    'E'
#define SORTIE    'S'
#define CHEMIN    'C'

const char tabchrLabyrinthe1[53][53] = {MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, ENTREE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, SORTIE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR,
                                        MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR};
const char tabchrLabyrinthe2[53][53] = {MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        ENTREE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, SORTIE, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR};
const char tabchrLabyrinthe3[53][53] = {MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR,
                                        MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR,
                                        MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE,
                                        MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR,
                                        MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR,
                                        MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE,
                                        MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, ENTREE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR,
                                        MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR,
                                        MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        MUR, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE,
                                        MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR,
                                        MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR,
                                        MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR,
                                        MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR,
                                        MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR,
                                        MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE,
                                        MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR,
                                        MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE,
                                        MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR,
                                        MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR,
                                        MUR, MUR, MUR, PASSAGE, MUR, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE,
                                        MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR,
                                        PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, SORTIE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE, MUR, PASSAGE, MUR,
                                        PASSAGE, MUR, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        PASSAGE, MUR, MUR, MUR, PASSAGE, MUR, PASSAGE, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, PASSAGE, MUR, MUR, MUR, PASSAGE, MUR,
                                        MUR, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE,
                                        PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, PASSAGE, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR, MUR,
                                        MUR, MUR, MUR};

#include<stdlib.h>
#include <time.h>
#include <SDL2/SDL.h>
#define LABYRINTHE tabchrLabyrinthe1

/*class TP1 {
private:
    SDL_Window *SDLWindow;
    SDL_Renderer *SDLRenderer;
    SDL_Event *SDLEvent;
    SDL_Rect SDLRect;
    bool boExecution;
public:
    TP1() {
        SDL_CreateWindowAndRenderer((sizeof(LABYRINTHE[0]) / sizeof(char)) * 10,
                                    ((sizeof(LABYRINTHE) / sizeof(LABYRINTHE[0])) / sizeof(char)) * 10, 0, &SDLWindow,
                                    &SDLRenderer);
        SDL_SetWindowTitle(SDLWindow, "420-P35-JO : TP1");
        boExecution = true;
        SDLRect.w = SDLRect.h = 10;
        SDLEvent = new SDL_Event();
    }

    ~TP1() {
        delete SDLEvent;
        SDL_DestroyRenderer(SDLRenderer);
        SDL_DestroyWindow(SDLWindow);
        SDL_Quit();
    }

    bool EnExecution() {
        while (SDL_PollEvent(SDLEvent))if (SDLEvent->type == SDL_QUIT)boExecution = false;
        SDL_RenderPresent(SDLRenderer);
        SDL_RenderClear(SDLRenderer);
        return boExecution;
    }

    void DessinerCarre(int _iX, int _iY, char _chrCouleur) {
        switch (_chrCouleur) {
            case MUR:
                SDL_SetRenderDrawColor(SDLRenderer, 63, 63, 70, 255);
                break;
            case PASSAGE:
                SDL_SetRenderDrawColor(SDLRenderer, 37, 37, 38, 255);
                break;
            case ENTREE:
                SDL_SetRenderDrawColor(SDLRenderer, 104, 33, 122, 255);
                break;
            case SORTIE:
                SDL_SetRenderDrawColor(SDLRenderer, 0, 122, 204, 255);
                break;
            case CHEMIN:
                SDL_SetRenderDrawColor(SDLRenderer, 21, 194, 60, 255);
                break;
        }
        SDLRect.x = _iX * 10;
        SDLRect.y = _iY * 10;
        SDL_RenderFillRect(SDLRenderer, &SDLRect);
    }
};*/